# Generated by Django 3.1.6 on 2021-03-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.opendining.net%2Fmenu%2F537f9c79f61e462455929f21&psig=AOvVaw2pRBdh5a5QQ8tffLRpLFi9&ust=1614791101120000&source=images&cd=vfe&ved=0CAYQjRxqFwoTCKjh4O-Lku8CFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
