# Generated by Django 3.1.6 on 2021-03-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_image',
            field=models.CharField(max_length=500),
        ),
    ]
