# Generated by Django 3.1.6 on 2021-03-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210302_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/532dfdbcc6479placeholder_food_item_2.png', max_length=500),
        ),
    ]
