# Generated by Django 3.1.6 on 2021-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210302_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_image',
            field=models.CharField(default='https://i.ebayimg.com/images/g/QloAAOSwejpfe1JN/s-l300.jpg', max_length=500),
        ),
    ]
